version: '3.8'

services:
  php:
    container_name: php
    build:
        context: ./
    ports:
      - '8080:80'
    volumes:
      - ../php:/var/www/html
  db:
    image: postgres:9.6
    container_name: db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${ROOT_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
